project:
  type: website

website:
  title: "Hien Bui"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: Resume
        href: resume.qmd
      - text: Projects
        menu:
          - text: EV Adoption
            href: projects/ev-adoption.qmd
          - text: Movie Recommender
            href: projects/movie-recommender.qmd
          - text: Book Ratings
            href: projects/book-ratings.qmd
          - text: Manga Sentiment
            href: projects/manga-sentiment.qmd
          - text: Luxury Car Price
            href: projects/luxury-car-price.qmd
      - text: Contact
        href: contact.qmd
    right:
      - icon: github
        href: https://github.com/krisauw
      - icon: linkedin
        href: https://www.linkedin.com/in/hien-bui-emi-6273b010a/
  search: true
  page-navigation: true

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 2
