project:
  type: website
  output-dir: docs
  execute-dir: project

# Publish these folders to docs/ so links work online
resources:
  - data/**
  - images/**
  - resume/**

website:
  title: "Hien Bui"
  search: true
  page-navigation: true
  navbar:
    background: "#2C3E50"   # dark blue
    foreground: light        # white text/icons
    left:
      - text: Home
        href: index.qmd
      - text: Resume
        href: resume.qmd
      - text: Projects
        menu:
          - text: EV Adoption in WA
            href: projects/ev-adoption.qmd
          - text: Movie Recommender
            href: projects/movie-recommender.qmd
          - text: Book Ratings
            href: projects/book-ratings.qmd
          - text: Manga Sentiment
            href: projects/manga-sentiment.qmd
          - text: Luxury Car Price
            href: projects/luxury-car-price.qmd
      - text: Contact
        href: contact.qmd
    right:
      - icon: github
        href: https://github.com/krisauw
      - icon: linkedin
        href: https://www.linkedin.com/in/hien-bui-emi-6273b010a/

format:
  html:
    theme: flatly 
    toc: true
    toc-depth: 2
    link-external-newwindow: true
    smooth-scroll: true
    code-fold: false
    code-copy: true
    code-overflow: wrap
    css: styles.css          # site-wide CSS (TOC + buttons color)

# Show code, don't execute, suppress messages
execute:
  eval: false
  echo: true
  warning: false
  error: false
