project:
  type: website
  output-dir: docs
  execute-dir: project

# Copy assets into docs/ when publishing
resources:
  - data/**
  - images/**

website:
  title: "Hien Bui"
  navbar:
    background: "#2C3E50"   # dark blue
    foreground: light
    left:
      - text: Home
        href: index.qmd
      - text: Resume
        href: resume.qmd
      - text: Projects
        menu:
          - text: EV Adoption in WA
            href: projects/ev-adoption.qmd
          - text: Movie Recommender
            href: projects/movie-recommender.qmd
          - text: Book Ratings
            href: projects/book-ratings.qmd
          - text: Manga Sentiment
            href: projects/manga-sentiment.qmd
          - text: Luxury Car Price
            href: projects/luxury-car-price.qmd
      - text: Contact
        href: contact.qmd
    right:
      - icon: github
        href: https://github.com/krisauw
      - icon: linkedin
        href: https://www.linkedin.com/in/hien-bui-emi-6273b010a/

execute:
  eval: false     # don't run any chunks
  echo: true      # DO show the code
  warning: false
  error: false
